# Generated by Django 5.0.7 on 2024-09-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transcend", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Languages",
            new_name="Language",
        ),
        migrations.RenameModel(
            old_name="Translations",
            new_name="Translation",
        ),
    ]
