# Generated by Django 5.0.7 on 2024-10-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcend', '0002_translationkey_rename_de_value_translation_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
