# Generated by Django 5.0.7 on 2024-10-02 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcend", "0003_alter_translation_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(
                choices=[("PL", "Polish"), ("DE", "German")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="transcend.language"
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=("key", "language"), name="unique_translation"
            ),
        ),
    ]
