# Generated by Django 5.0.7 on 2024-10-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcend', '0004_remove_translation_unique_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='translation_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_key', to='transcend.translationkey'),
        ),
    ]
