# Generated by Django 5.0.7 on 2024-10-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcend', '0004_alter_language_code_alter_translation_language_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translation',
            name='unique_translation',
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('id', 'language'), name='unique_translation'),
        ),
    ]
